POST   http://localhost:3003/notify
content-type: application/json
//Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyOSwiZm5hbWUiOiJZb3Vzc2VmIiwibG5hbWUiOiJBem91Z2FnaCIsImVtYWlsIjoiYWRtaW5AaW1tZXJzZS5jb20iLCJpYXQiOjE3MDA3OTg2OTUsImV4cCI6MTcwMDgzNDY5NX0.63u8XNt_-5UzzaR-nET5-ZiXmiAonnm62sKJCAd_9rY"

{
   "eventType":"imLoggedIn",
   "user_id":40,
    "contact_id":29
}
  