GET  http://localhost:3001/api/users/me
content-type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MCwidXNlcm5hbWUiOiJ5b3Vzc2VmLmF6b3VnYWdoOTZAZ21haWwuY29tIiwiZm5hbWUiOiJZb3Vzc2VmIiwibG5hbWUiOiJBem91Z2FnaCIsImlhdCI6MTcwMDYzOTI3MiwiZXhwIjoxNzAwNjQyODcyfQ.7GfJlpGiAwAQZw9LjJae2DN5Vh3lwh5Lfvyj1mrvDNo"
//    "email":"youssef.azougagh96@gmail.com",
 //   "password":"password",
   // "verifCode":"0f25"
//}
 