GET   http://localhost:3001/api/users/accept-contact/29/40
content-type: application/json
//Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyOSwiZm5hbWUiOiJZb3Vzc2VmIiwibG5hbWUiOiJBem91Z2FnaCIsImVtYWlsIjoiYWRtaW5AaW1tZXJzZS5jb20iLCJpYXQiOjE3MDA3OTg2OTUsImV4cCI6MTcwMDgzNDY5NX0.63u8XNt_-5UzzaR-nET5-ZiXmiAonnm62sKJCAd_9rY"

{
   "email":"josephinejoe69@gmail.com",
   "password":"password",
    "fname":"Youssef",
    "lname":"Azougagh",
    "referrer":"29"
}
  