-- MySQL Script generated by MySQL Workbench
-- Fri Oct  6 18:29:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema immerse
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `immerse` ;

-- -----------------------------------------------------
-- Schema immerse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `immerse` DEFAULT CHARACTER SET utf8 ;
USE `immerse` ;

-- -----------------------------------------------------
-- Table `immerse`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immerse`.`User` (
  `user_id` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `last_seen` TIMESTAMP NULL,
  `about` VARCHAR(200) NULL DEFAULT 'Null',
  `image` BLOB NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `iduser_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immerse`.`Conversation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immerse`.`Conversation` (
  `conv_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT 'Null',
  PRIMARY KEY (`conv_id`),
  UNIQUE INDEX `conv_id_UNIQUE` (`conv_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immerse`.`UserHasContact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immerse`.`UserHasContact` (
  `user_id` VARCHAR(45) NOT NULL,
  `contact_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`, `contact_id`),
  INDEX `fk_UserHasContact_User2_idx` (`contact_id` ASC) VISIBLE,
  CONSTRAINT `fk_UserHasContact_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `immerse`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserHasContact_Contact`
    FOREIGN KEY (`contact_id`)
    REFERENCES `immerse`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immerse`.`ConversationHasParticipant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immerse`.`ConversationHasParticipant` (
  `user_id` VARCHAR(45) NOT NULL,
  `conv_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `conv_id`),
  INDEX `fk_ConversationHasParticipant_User1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_ConversationHasParticipant_Conversation1_idx` (`conv_id` ASC) VISIBLE,
  CONSTRAINT `fk_ConversationHasParticipant_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `immerse`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConversationHasParticipant_Conversation1`
    FOREIGN KEY (`conv_id`)
    REFERENCES `immerse`.`Conversation` (`conv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immerse`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immerse`.`Message` (
  `msg_id` INT NOT NULL AUTO_INCREMENT,
  `content` BLOB NOT NULL,
  `content_type` ENUM('msg', 'media') NOT NULL,
  `status` ENUM('pending', 'delivered', 'seen') NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `conv_id` INT NOT NULL,
  `sender_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`msg_id`, `conv_id`, `sender_id`),
  INDEX `fk_Message_Conversation1_idx` (`conv_id` ASC) VISIBLE,
  INDEX `fk_Message_User1_idx` (`sender_id` ASC) VISIBLE,
  CONSTRAINT `fk_Message_Conversation1`
    FOREIGN KEY (`conv_id`)
    REFERENCES `immerse`.`Conversation` (`conv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_Sender`
    FOREIGN KEY (`sender_id`)
    REFERENCES `immerse`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
