export const CHAT_USER = 'CHAT_USER';
export const ACTIVE_USER = 'ACTIVE_USER';
export const FULL_USER = 'FULL_USER';
export const ADD_LOGGED_USER = 'ADD_LOGGED_USER';
export const CREATE_GROUP = 'CREATE_GROUP';

export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';

export const FETCH_USER_CONTACTS = 'FETCH_USER_CONTACTS';
export const FETCH_USER_CONTACTS_SUCCESS = 'FETCH_USER_CONTACTS_SUCCESS';

export const INVITE_CONTACT = 'INVITE_CONTACT';
export const INVITE_CONTACT_SUCCESS = 'INVITE_CONTACT_SUCCESS';

export const FETCH_USER_MESSAGES = 'FETCH_USER_MESSAGES';
export const FETCH_USER_MESSAGES_SUCCESS = 'FETCH_USER_MESSAGES_SUCCESS';
