export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';

export const CODE_SENT = 'CODE_SENT';
export const CODE_SENT_SUCCESS = 'CODE_SENT_SUCCESS';

export const API_FAILED = 'AUTH_API_FAILED';


export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

export const FETCH_USER_CONTACTS = "FETCH_USER_CONTACTS";
export const FETCH_USER_CONTACTS_SUCCESS = "FETCH_USER_CONTACTS_SUCCESS";